=== libreccm/ccm/tools-ng/common/xsd/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
  xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:ccm="http://ccm.redhat.com/ccm-project"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  targetNamespace="http://ccm.redhat.com/ccm-project">

  <element name="project">
    <complexType>
      <all>
        <element name="databases" type="ccm:databases" minOccurs="0">
          <annotation>
            <documentation xml:lang="en">
              The list of databases to generate SQL for. If omitted
              defaults to all currently supported databases
            </documentation>
          </annotation>
        </element>

        <element name="options" type="ccm:options" minOccurs="0">
          <annotation>
            <documentation xml:lang="en">
              The list of general project options.
            </documentation>
          </annotation>
        </element>

        <element name="build" type="ccm:build" minOccurs="0">
          <annotation>
            <documentation xml:lang="en">The list of local applications to build and deploy</documentation>
          </annotation>
        </element>
        <element name="prebuilt" type="ccm:prebuilt" minOccurs="0">
          <annotation>
            <documentation xml:lang="en">The list of pre-built applications to deploy</documentation>
          </annotation>
        </element>
      </all>

      <attribute name="name" type="string">
        <annotation>
          <documentation xml:lang="en">The name of the bundle packages to generate, eg RPMs, ZIPs</documentation>
        </annotation>
      </attribute>

      <attribute name="prettyName" type="string">
        <annotation>
          <documentation xml:lang="en">The human readable package name</documentation>
        </annotation>
      </attribute>

      <attribute name="ccmVersion" type="ccm:ccmVersion" use="optional">
        <annotation>
          <documentation xml:lang="en">
            The CCM version for build tools. Corresponds to version of Core being used.
            If omitted assumes 5.x build compatability.
          </documentation>
        </annotation>
      </attribute>

      <attribute name="type" type="string" use="optional">
        <annotation>
          <documentation xml:lang="en">The type of project</documentation>
        </annotation>
      </attribute>

      <attribute name="version" type="ccm:version">
        <annotation>
          <documentation xml:lang="en">The version number for the bundle packages</documentation>
        </annotation>
      </attribute>

      <attribute name="release" type="integer">
        <annotation>
          <documentation xml:lang="en">The release number for the bundle packages</documentation>
        </annotation>
      </attribute>

      <attribute name="webxml" type="string" use="optional">
        <annotation>
          <documentation xml:lang="en">The file to be copied to web.xml in the ROOT webapp upon deployment.</documentation>
        </annotation>
      </attribute>

    </complexType>

    <unique name="unique_prebuilt">
      <selector xpath="ccm:prebuilt/ccm:application"/>
      <field xpath="@name"/>
    </unique>

    <unique name="unique_build">
      <selector xpath="ccm:build/ccm:application"/>
      <field xpath="@name"/>
    </unique>

  </element>

  <complexType name="databases">
    <sequence>
      <element name="database" minOccurs="1" maxOccurs="unbounded">
        <annotation>
          <documentation xml:lang="en"></documentation>
        </annotation>
        <complexType>
          <attribute name="name" type="ccm:database"/>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="options">
    <sequence>
      <element name="option" type="ccm:option" minOccurs="0" maxOccurs="unbounded">
        <annotation>
          <documentation xml:lang="en"></documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>

  <complexType name="build">
    <sequence>
      <element name="application" type="ccm:buildapp" minOccurs="0" maxOccurs="unbounded">
        <annotation>
          <documentation xml:lang="en">An local application to build</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>

  <complexType name="prebuilt">
    <sequence>
      <element name="application" type="ccm:prebuiltapp" minOccurs="0" maxOccurs="unbounded">
        <annotation>
          <documentation xml:lang="en">A pre-built application to deploy</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>

  <complexType name="buildapp">
    <attribute name="name">
      <annotation>
        <documentation xml:lang="en">
          The name of the application. Refers to the name of the directory
          containing the application.
        </documentation>
      </annotation>
    </attribute>
    <attribute name="prettyName" use="optional">
      <annotation>
        <documentation xml:lang="en">The human friendly name of the application</documentation>
      </annotation>
    </attribute>
    <attribute name="buildOrder" use="optional">
      <annotation>
        <documentation xml:lang="en">Order in which to deploy the applications</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="prebuiltapp">
    <attribute name="name">
      <annotation>
        <documentation xml:lang="en">The name of the application</documentation>
      </annotation>
    </attribute>
    <attribute name="version" type="ccm:version">
      <annotation>
        <documentation xml:lang="en">The version number of the application</documentation>
      </annotation>
    </attribute>
    <attribute name="buildOrder" use="optional">
      <annotation>
        <documentation xml:lang="en">Order in which to deploy the applications</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="option">
    <attribute name="name">
      <annotation>
        <documentation xml:lang="en">The name of the options</documentation>
      </annotation>
    </attribute>
    <attribute name="value">
      <annotation>
        <documentation xml:lang="en">The value of the options</documentation>
      </annotation>
    </attribute>
  </complexType>

  <simpleType name="database">
    <annotation>
      <documentation xml:lang="en">A enumeration of supported databases</documentation>
    </annotation>

    <restriction base="string">
      <enumeration value="postgres"/>
      <enumeration value="oracle-se"/>
    </restriction>
  </simpleType>


  <simpleType name="ccmVersion">
    <annotation>
      <documentation xml:lang="en">A enumeration of build tool compatability versions</documentation>
    </annotation>

    <restriction base="string">
      <enumeration value="5x"/>
      <enumeration value="6.0"/>
      <enumeration value="6.1"/>
    </restriction>
  </simpleType>

  <simpleType name="version">
    <annotation>
      <documentation xml:lang="en">A version number made up of three dot separated integers</documentation>
    </annotation>

    <restriction base="string">
      <pattern value="\d+\.\d+\.\d+"/>
    </restriction>
  </simpleType>
</schema>

=== libreccm/ccm/ccm-ldn-aplaws/bundles/demo/cfg/project.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- project.xml - (ldn)demo - containing the same set of modules as the
     extended set, with a complete, ready to run pre-configuration. 
     Has to keep synchronized with the extended bundle!                      -->

<ccm:project   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xmlns:ccm="http://ccm.redhat.com/ccm-project" 
              ccmVersion="6.1" 
                    name="aplaws" 
              prettyName="APLAWS plus Demo Spin"
                 version="1-1-5" 
                 release="-demo" 
                  webxml="web.xml-aplaws" 
                  webapp="ROOT"
      xsi:schemaLocation="http://ccm.redhat.com/ccm-project file:tools-ng/common/xsd/project.xsd">

<ccm:databases>
        <ccm:database name="postgres"/>
</ccm:databases>


  <ccm:build>
        <!--  Main apps   -->
        <ccm:application name="ccm-core"/>
        <ccm:application name="ccm-cms"/>

        <!--  Content assets   -->
        <ccm:application name="ccm-cms-assets-fileattachment"/>
        <ccm:application name="ccm-cms-assets-imagestep"/>
        <ccm:application name="ccm-cms-assets-notes"/>
        <ccm:application name="ccm-cms-assets-relatedlink"/>

        <!--  Content types   -->
        <ccm:application name="ccm-cms-types-agenda"/>
        <ccm:application name="ccm-cms-types-article"/>
        <ccm:application name="ccm-cms-types-bookmark"/>
        <ccm:application name="ccm-cms-types-contact"/>
        <ccm:application name="ccm-cms-types-esdservice"/>
        <ccm:application name="ccm-cms-types-event"/>
        <ccm:application name="ccm-cms-types-faqitem"/>
        <ccm:application name="ccm-cms-types-filestorageitem"/>
        <ccm:application name="ccm-cms-types-formitem"/>
        <ccm:application name="ccm-cms-types-formsectionitem"/>
        <ccm:application name="ccm-cms-types-glossaryitem"/>
        <ccm:application name="ccm-cms-types-htmlform"/>
        <ccm:application name="ccm-cms-types-image"/>
        <ccm:application name="ccm-cms-types-inlinesite"/>
        <ccm:application name="ccm-cms-types-job"/>
        <ccm:application name="ccm-cms-types-legalnotice"/>
        <ccm:application name="ccm-cms-types-minutes"/>
        <ccm:application name="ccm-cms-types-mparticle"/>
        <ccm:application name="ccm-cms-types-newsitem"/>
        <ccm:application name="ccm-cms-types-organization"/>
        <ccm:application name="ccm-cms-types-pressrelease"/>
        <ccm:application name="ccm-cms-types-service"/>
        <ccm:application name="ccm-cms-types-simpleaddress"/>
        <!-- siteproxy is a prerequisite for ccm-ldn-atoz  -->
        <ccm:application name="ccm-cms-types-siteproxy"/>
        <ccm:application name="ccm-cms-types-xmlfeed"/>

        <!--  Applications   -->
        <ccm:application name="ccm-ldn-aplaws"/>
        <ccm:application name="ccm-ldn-atoz"/>
        <ccm:application name="ccm-ldn-dublin"/>
        <ccm:application name="ccm-ldn-exporter"/>
        <ccm:application name="ccm-ldn-freeform"/>
        <ccm:application name="ccm-ldn-importer"/>
        <ccm:application name="ccm-ldn-navigation"/>
        <ccm:application name="ccm-ldn-rss"/>
        <ccm:application name="ccm-ldn-search"/>
        <ccm:application name="ccm-ldn-shortcuts"/>
        <ccm:application name="ccm-ldn-subsite"/>
        <ccm:application name="ccm-ldn-terms"/>
        <ccm:application name="ccm-ldn-util"/>

        <!--  Extra apps   -->
        <ccm:application name="ccm-docrepo"/>
        <ccm:application name="ccm-faq"/>
        <ccm:application name="ccm-forum"/>     
        <ccm:application name="ccm-forum-categorised"/>     
        <ccm:application name="ccm-portalserver"/>
        <ccm:application name="ccm-portalworkspace"/>
        <ccm:application name="ccm-themedirector"/>


<!-- tools will be downloaded from trunk, but does not
     contain java code to be compiled!
        <ccm:application name="tools"/>           -->


  </ccm:build>
</ccm:project>
