=== libreccm/ccm/ccm-core/test/src/com/arsdigita/persistence/metadata/data/metadata.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!-- DTD for the metadata system -->

<!ELEMENT metadataroot (model|schema)+>

<!ELEMENT model (association|objecttype)+>

<!ELEMENT schema (foreignkey|table)+>

<!ELEMENT association (associationmap|associationrole|linkattribute)+>

<!ELEMENT foreignkey (columnref|uniquekeyref)+>

<!ELEMENT objecttype (attribute|objectmap|rolereference|supertyperef)+>

<!ELEMENT table (column|primarykey|uniquekey)+>

<!ELEMENT associationmap (associationmapentry|foreignkey)+>

<!ELEMENT associationrole (multiplicity|objecttyperef)+>

<!ELEMENT attribute (multiplicity)+>
<!ATTLIST attribute
     datatype    (Boolean | Integer | Date | String)    #REQUIRED
>

<!ELEMENT column EMPTY>
<!ATTLIST column
     datatype    CDATA    #REQUIRED
>

<!ELEMENT columnref EMPTY>

<!ELEMENT linkattribute EMPTY>
<!ATTLIST linkattribute
     datatype    (String)    #REQUIRED
>

<!ELEMENT objectmap (extendedmapentry|foreignkey|objectkey|objectmapentry)+>

<!ELEMENT primarykey (columnref)+>

<!ELEMENT rolereference (associationroleref)+>

<!ELEMENT supertyperef EMPTY>

<!ELEMENT uniquekey (columnref)+>

<!ELEMENT uniquekeyref EMPTY>

<!ELEMENT associationmapentry (columnref|linkattributeref)+>

<!ELEMENT associationroleref EMPTY>

<!ELEMENT extendedmapentry (attributeref|extensiontable)+>

<!ELEMENT multiplicity EMPTY>
<!ATTLIST multiplicity
     lowerbound    CDATA    #REQUIRED
     upperbound    CDATA    #REQUIRED
>

<!ELEMENT objectkey (attributeref)+>

<!ELEMENT objectmapentry (attributeref|columnref)+>

<!ELEMENT objecttyperef EMPTY>

<!ELEMENT attributeref EMPTY>

<!ELEMENT extensiontable (attributecolumnref|foreignkey|valuecolumnref)+>

<!ELEMENT linkattributeref EMPTY>

<!ELEMENT attributecolumnref EMPTY>

<!ELEMENT valuecolumnref EMPTY>

=== libreccm/ccm/ccm-core/test/src/com/arsdigita/persistence/metadata/data/basic-schema.xml
<?xml version='1.0' encoding='utf-8'?> 
<!DOCTYPE metadataroot SYSTEM "metadata.dtd">

<metadataroot name="acs" version="4.0">
  <schema name="oracle" id="acs:oracle">
    <table name="ACS_OBJECTS" id="acs:oracle:acs_objects">
      <column name="CONTEXT_ID" datatype="BIGINT" id="acs:oracle:acs_objects:context_id"/>
      <column name="OBJECT_ID" datatype="BIGINT" id="acs:oracle:acs_objects:object_id"/>
      <column name="OBJECT_TYPE" datatype="VARCHAR(100)" id="acs:oracle:acs_objects:object_type"/>
      <uniquekey id="acs:oracle:acs_objects_context_object_un">
        <columnref idref="acs:oracle:acs_objects:object_id"/>
        <columnref idref="acs:oracle:acs_objects:context_id"/>
      </uniquekey>
      <primarykey id="acs:oracle:acs_objects_pk">
        <columnref idref="acs:oracle:acs_objects:object_id"/>
      </primarykey>
    </table>
    <table name="PARTIES" id="acs:oracle:parties">
      <column name="EMAIL" datatype="VARCHAR(100)" id="acs:oracle:parties:email"/>
      <column name="PARTY_ID" datatype="BIGINT" id="acs:oracle:parties:party_id"/>
      <column name="URL" datatype="VARCHAR(200)" id="acs:oracle:parties:url"/>
      <uniquekey id="acs:oracle:parties_email_un">
        <columnref idref="acs:oracle:parties:email"/>
      </uniquekey>
      <primarykey id="acs:oracle:parties_party_id_pk">
        <columnref idref="acs:oracle:parties:party_id"/>
      </primarykey>
    </table>
    <foreignkey id="acs:oracle:parties_party_id:acs_object_pk">
      <columnref idref="acs:oracle:parties:party_id"/>
      <uniquekeyref idref="acs:oracle:acs_objects_pk"/>
    </foreignkey>
  </schema>
</metadataroot>
